title: Matias Zilli | Personal Portfolio
url: "https://matiaszilli.github.io"
baseurl: ""
bio-page-label: CV
theme-home: theme-home-builtin-1.html
theme-projects: theme-projects-builtin-1.html
theme-essays: theme-essays-builtin-1.html
theme-bio: theme-bio-builtin-1.html

rouge-theme: igorpro

markdown: kramdown
include: [_data]

